package CRT;

public class program2 {
	public static void main(String[] args) {
		int limit = 4000000;
		int ans = evenFiboSeries(limit);
		System.out.println(ans);
	}
	public static int evenFiboSeries(int end) {
		int a=1, b=2, sum=0;
		while(a <= end ) {
			if(a%2==0) {
				sum+=a;
			}
			int t=a;
			a=b;
			b=t+b;
		}
		return sum;
	}

}

/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 
and 
, the first 
terms will be: 

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/



//Answer:  4613732